junit_patterns:
- ben10/pytest.xml

platform-windows:build_batch_commands:
- %AA_AASIMAR_AA_CONFIG% --conf-dir=%WORKSPACE% --projects-dir=%WORKSPACE% --dist-dirname=dist-development --dist={dist} --platform={platform} --reset-env --load-env=ben10
- python ben10/ci.py

platform-linux:build_shell_commands:
- $AA_AASIMAR_AA_CONFIG --conf-dir=$WORKSPACE --projects-dir=$WORKSPACE --dist={dist} --platform={platform} --reset-env --load-env=ben10
- python ben10/ci.py

description_regex: "HUDSON DESCRIPTION\\: (.*)"

matrix:
  dist:
  - 12.0

  platform:
  - win32,windows
  - win64,windows
  - redhat64,linux

