junit_patterns:
- ben10/pytest.xml

platform-windows:build_batch_commands:
- |
  %AA_AASIMAR_AA% -t project.build ben10 --projects-dir=%WORKSPACE% --dist={dist} --platform={platform} --dist-dirname=dist-development
  %AA_AASIMAR_AA% -t ar.pak        ben10 --projects-dir=%WORKSPACE% --dist={dist} --platform={platform} --branch={branch}


platform-linux:build_shell_commands:
- |
  $AA_AASIMAR_AA  -t project.build ben10 --projects-dir=$WORKSPACE  --dist-dirname=dist-development --dist={dist} --platform={platform}


description_regex: "DESCRIPTION\\: (.*)"

matrix:
  dist:
  - 12.0

  platform:
  - win32,windows
  - win64,windows
  - redhat64,linux

display_name: "[{branch}] {name} {dist}-{platform}"

