junit_patterns:
- "**/build/{dist}-{platform}-tests/*.xml"

platform-windows:build_batch_commands:
- |
  %AA_AASIMAR_AA_CONFIG% --aasimar-ref=origin/master --dist-ref=origin/master --projects-dir=%WORKSPACE% --dist={dist} --platform={platform} --conf-dir=%WORKSPACE% --reset-env --load-env=git || goto :eof
  %AA_AASIMAR_AA% -t project.build ben10  || goto :eof
  %AA_AASIMAR_II% pak              ben10 --branch={branch}


platform-linux:build_shell_commands:
- |
  $AA_AASIMAR_AA_CONFIG --aasimar-ref=origin/master --dist-ref=origin/master --projects-dir=$WORKSPACE --dist={dist} --platform={platform} --conf-dir=$WORKSPACE --reset-env --load-env=git
  $AA_AASIMAR_AA -t project.build ben10


description_regex: "DESCRIPTION\\: (.*)"

matrix:
  dist:
  - 12.0

  platform:
  - win32,windows
  - win64,windows
  - redhat64,linux

label_expression: "{platform} && {name} && team-bos"

display_name: "[{branch}] {name} {dist}-{platform}"

branch_patterns:
- master
- fb-*
- ama*

notify_stash:

timeout: 5

git:
  reference: "$AA_SYSTEM_REF_REPOS/{name}"

