junit_patterns:
- "**/build/{dist}-{platform}-tests/*.xml"

platform-windows:build_batch_commands:
- |
  %AA_AASIMAR_AA% -t project.build ben10 --projects-dir=%WORKSPACE% --dist={dist} --platform={platform}
  %AA_AASIMAR_II% pak              ben10 --projects-dir=%WORKSPACE% --dist={dist} --platform={platform} --branch={branch}


platform-linux:build_shell_commands:
- |
  $AA_AASIMAR_AA  -t project.build ben10 --projects-dir=$WORKSPACE --dist={dist} --platform={platform}


description_regex: "DESCRIPTION\\: (.*)"

matrix:
  dist:
  - 12.0

  platform:
  - win32,windows
  - win64,windows
  - redhat64,linux

display_name: "[{branch}] {name} {dist}-{platform}"

branch_patterns:
- master
- fb-*
- ama*

