language: python
python:
    - 2.7
install:
    - sudo apt-get install -qq unrar
    - pip install --use-wheel -r requirements.txt
    - pip install --use-wheel coveralls
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
	- git config --global user.email "travisci@ben10.com"
	- git config --global user.name "Travis CI Ben10"
	- git config --global log.date iso
script:
    - coverage run --source=source setup.py test
after_success:
    - coveralls
