language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
install:
- sudo apt-get install -qq unrar
- pip install --use-wheel -r requirements.txt
- pip install --use-wheel coveralls
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
- coverage run --source=source setup.py test
after_success:
- coveralls
