language: python
python:
    - 2.7
install:
    - sudo apt-get install -qq unrar
    - pip install --use-wheel -r requirements.txt
    - pip install --use-wheel coveralls
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
    - coverage run --source=source setup.py test
after_success:
    - coveralls
notifications:
    slack: esss:X8WNRDb8Ih8Wh3O7Rio513vO
