name: ben10

includes:
  - {{ root }}/../aasimar/environment.yml

dependencies:
  - cogapp==2.4
  - colorama==0.3.3
  - cov-core==1.15.0
  - coverage==3.7.1
  - desktop==0.4.2
  - execnet==1.2
  - faulthandler==2.3
  - ftputil==3.2
  - futures==2.2.0
  - git==2.4.4
  - gprof2dot==2015.02.03
  - logilab-astng==0.24.3
  - logilab-common==0.60.0
  - mock==1.0.1
  - path.py==7.3
  - pyftpdlib==1.4.0
  - pyopenssl==0.15.1
  - pytest==2.7.0
  - pytest-cov==1.8.1
  - pytest-localserver==0.3.3
  - pytest-timeout==0.4
  - pytest-xdist==1.12
  - rarfile==2.7
  - ruamel.ordereddict==0.4.6
  - setuptools==12.2
  - werkzeug==0.10.4

environment:
  - PYTHONPATH:
    - {{ root }}/source/python

